POST http://localhost:3001/api/bills
Content-Type: application/json

{
    "date": "2025-01-11",
    "category": "Supermarket",
    "description": "Lidle",
    "amount": "62",
    "userId": "678828c363011443c88e3384"
}


