POST http://localhost:3001/api/bills
Content-Type: application/json
Authorization: Bearer 'token'

{
    "date": "2025-01-15",
    "category": "Car",
    "description": "Parking",
    "amount": "15"
}


